#!/usr/bin/env python
#-*- coding:utf-8 -*-
from sys import exit
from termcolor import cprint
from config import config
from javascript import get_commit_errors as get_javascript_errors

if __name__ == "__main__":
  javascript_errors = get_javascript_errors()
  if not javascript_errors:
    exit(0)

  cprint("CodeSniffer check result: \n", "magenta")
  if javascript_errors:
    print(javascript_errors)

  exit(config.getboolean("commit", "REJECT_COMMIT"))
