#!/usr/bin/env node

if (process.argv.indexOf("--config") === -1) {
  process.argv.push("--config");
  process.argv.push(__dirname + "/../configs/jshint.json");
}

require("./cli").interpret(process.argv);
